### ISSUE TITLE
Options for injecting JavaScript to run on the page before taking the screenshot

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#12]
This is the starting point for fancy features like the arrow annotations described in these two issues:
- #9
- #10

**Comment by simonw** [comment]
For the `shot` command:

```
shot-scraper https://simonwillison.net/ -o simonwillison.png --javascript "
document.body.style.backgroundColor = 'pink';
"
```
In YAML:
```yaml
- output: simonwillison-bighead.png
  url: https://simonwillison.net/
  selector: "#bighead"
  javascript: |
    document.body.style.backgroundColor = 'pink'
```
