### ISSUE TITLE
Build a live demo of shot-scraper

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#14]
A live demo running in a GitHub repo to show what a daily scrape could look like.

**Comment by simonw** [comment]
I want something where I can take a screenshot every day of an area of the page that isn't *too* large but results in a history that's fun to look at with the GitHub image diff tool.

**Comment by simonw** [comment]
I'm going to use https://www.owlsnearme.com/?place=127871 for the area near us, and I'll take a screenshot of the part of the page that shows recent owl sightings.

Two catches. First, I tried this and the images hadn't loaded yet - so I needed a delay. This fixed that:

    shot-scraper 'https://www.owlsnearme.com/?place=127871' \
      --selector 'section.secondary' \
      --javascript 'new Promise(resolve => setTimeout(resolve, 2000))' \
      -o owls.jpg

Secondly, it's still a bit too big - there are 30 images in that area. I'm going to trim it down to just the first 9 using:

    Array.from(
      document.querySelectorAll('section.secondary .spotting')
    ).splice(9).forEach(el => el.parentNode.removeChild(el))

**Comment by simonw** [comment]
```
shot-scraper 'https://www.owlsnearme.com/?place=127871' \
  --selector 'section.secondary' \
  --javascript '
    new Promise(resolve => setTimeout(() => {
      Array.from(
        document.querySelectorAll("section.secondary .spotting")
      ).splice(9).forEach(el => el.parentNode.removeChild(el))
       resolve();
    }, 2000))' \
  --quality 80 \
  -o owls.jpg
```

**Comment by simonw** [comment]
With `--wait` the above becomes:
```
shot-scraper 'https://www.owlsnearme.com/?place=127871' \
  --selector 'section.secondary' \
  --wait 3000 \
  --javascript '
  Array.from(
    document.querySelectorAll("section.secondary .spotting")
  ).splice(9).forEach(el => el.parentNode.removeChild(el))
  ' \
  --quality 50 \
  -o owls.jpg
```

**Comment by simonw** [comment]
I used this YAML:
```yaml
- url: https://www.owlsnearme.com/?place=127871
  selector: 'section.secondary'
  wait: 3000
  javascript: |
    Array.from(
      document.querySelectorAll("section.secondary .spotting")
    ).splice(9).forEach(el => el.parentNode.removeChild(el))
  quality: 50
  output: examples/owls.jpg
```

**Comment by simonw** [comment]
I'm going to ship 0.3 with `--wait` and a link to the demo repo even though it's not running yet.

**Comment by simonw** [comment]
I should cache the Playwright browsers. Found this via GitHub code search:
```yaml
      - name: Cache Playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers
```
