### ISSUE TITLE
`shot-scraper multi` mechanism for running commands between shots

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#155]
This came up here:
- https://github.com/simonw/django-screenshots/issues/4

When taking a sequence of screenshots it can be useful to run other commands in between shots - to modify the Django app that is being documented, for example.

`shot-scraper` could support this in the `shot-scraper multi shots.yml` YAML format.

**Comment by simonw** [comment]
Current file format:
```yaml
- output: js-selector-all.png
  url: https://github.com/simonw/shot-scraper
  js_selector: |-
    el.tagName == "P" && el.innerText.includes("shot-scraper")
  padding: 20
- output: bighead-pink.png
  url: https://simonwillison.net/
  selector: "#bighead"
  javascript: |
    document.body.style.backgroundColor = 'pink'
```
I could introduce new types of block that don't have a `url: ` key. Maybe these:

```yaml
- shell: echo "hello world" > index.html
```
Or:
```yaml
- python: |
    open("index.html", "w").write("hello world")
```
