### ISSUE TITLE
Test failure: Timed out while waiting for element to become available.

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#158]
Got this on https://github.com/simonw/shot-scraper/actions/runs/11063153856/job/30738817452
```
Screenshot of '#bighead, .overband' on 'https://simonwillison.net/' written to 'examples/bighead-multi-selector.png'
Error: Timed out while waiting for element to become available.

Locator.screenshot: Timeout 29952ms exceeded.
Call log:
taking element screenshot
  - waiting for fonts to load...
  - fonts loaded
  - attempting scroll into view action
  -   waiting for element to be stable
  -   element is not visible
  ...
```

**Comment by simonw** [comment]
Relevant snippet of tests (I think): https://github.com/simonw/shot-scraper/blob/a5e9707ed343e1acd35fccf8e4ebe35fe4e62425/tests/run_examples.sh#L23-L45

**Comment by simonw** [comment]
Here's the problem:
```bash
shot-scraper https://simonwillison.net/ \
   --selector-all .day --padding 20 \
   -o examples/selector-all.png
```
I redesigned my blog and removed the `.day` bit a while ago.

**Comment by simonw** [comment]
I'll do this instead:
```bash
shot-scraper https://simonwillison.net/ \
   --selector-all '#secondary li:nth-child(-n+5)' \
   --padding 20 \
   -o examples/selector-all.png
```
![selector-all](https://github.com/user-attachments/assets/5e330bcb-57d3-4fe1-a72b-394c2c1139ce)

**Comment by simonw** [comment]
Stil getting an error - this time I can recreate with `bug.yaml`:
```yaml
- output: selectors-all-from-multi.png
  url: https://simonwillison.net/
  selectors_all:
  - #secondary li:nth-child(-n+5)
  - .entry:nth-of-type(1)
  padding: 20
```
And then:

    shot-scraper multi bug.yaml

```
Error: Timed out while waiting for element to become available.

Timeout 29963ms exceeded.
=========================== logs ===========================
taking element screenshot
  waiting for element to be visible and stable
    element is not visible - waiting...
============================================================
```

**Comment by simonw** [comment]
I'll do this instead:
```yaml
- output: selectors-all-from-multi.png
  url: https://simonwillison.net/
  selectors_all:
  - "#secondary li:nth-child(-n+5)"
  - "#secondary li:nth-child(8)"
  padding: 20
```
