### ISSUE TITLE
YAML configuration for PDF shots

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#27]
I added PDF support here:
- #24

But there's currently no way to script PDFs in the YAML syntax with `shot-scraper multi`. This would be really useful, especially as the PDF generation grows even more options:
- #26

**Comment by simonw** [comment]
This could work:
```yaml
- output: example.pdf
  pdf: true
  url: http://www.example.com/
```
