### ISSUE TITLE
`--selector-all` to screenshot of all elements matching a selector

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#64]
> This then made me think that I actually want the same ability for just raw CSS selectors. But what should that look like?

_Originally posted by @simonw in https://github.com/simonw/shot-scraper/issues/43#issuecomment-1095338690_

**Comment by simonw** [comment]
I found myself wanting to take a screenshot of e.g. all of the SVGs on a page - so a box that is drawn around all of those elements.

Right now the `-s/--selector` option takes just the first element that matches a selector - though you can use it multiple times to specify other selectors too:

```
shot-scraper https://simonwillison.net/ \
  -s '#bighead' -s .overband \
  -o bighead-multi-selector.png
```

I think a `--selector-all` option may be the best way to do this.

Then I could have `--js-selector-all` as the equivalent for this new feature:
- #43

**Comment by simonw** [comment]
Open questions: How should that work in the `multi` YAML format?

**Comment by simonw** [comment]
Relevant code: https://github.com/simonw/shot-scraper/blob/f66274657ca81d1d3867b2109a215fc18b9ae9d2/shot_scraper/cli.py#L655-L665

It uses `querySelector()` but for this feature it could use `querySelectorAll`.

**Comment by simonw** [comment]
I like that `--selector-all` is to `querySelectorAll()` as `--selector` is to `querySelector()`.

**Comment by simonw** [comment]
I'm going to add `selector_all:` and `selectors_all:` as the YAML keys, similar to `selector:` and `selectors:`.

(Going with Attorneys General pluralization here.)

**Comment by simonw** [comment]
With the new feature:

    shot-scraper https://simonwillison.net/ --selector-all '.day' --padding 10

![simonwillison-net 11](https://user-images.githubusercontent.com/9599/162800829-d26ed37c-df0c-4b22-ab7c-82cf87d6f5e2.png)

**Comment by simonw** [comment]
And for `shot-scraper multi`:

```
echo '- output: selectors-all.png
  url: https://simonwillison.net/
  selectors_all:
  - .day
  - .entry:nth-of-type(1)
  padding: 20' | shot-scraper https://simonwillison.net/
```
Produced this:

![selectors-all](https://user-images.githubusercontent.com/9599/162801767-a91f3092-35a8-43b2-ae12-049b0a83fbc3.png)

**Comment by simonw** [comment]
Also manually tested with this:
```
echo '- output: selector-all.png
  url: https://simonwillison.net/
  selector_all:
  - .day
  padding: 20' | shot-scraper https://simonwillison.net/
```
