### ISSUE TITLE
Idea/Question: Define global parameters and placeholders?

### ISSUE THREAD

**Issue by patowod** [simonw/shot-scraper#79]
Foremost: This is a fantastic tool. Thank you! 

I've managed to get everything up and running, but wonder if I am able to realise my use case: I often need to take multiple variants of screenshots for multiple URLs. An example would be: I have ten different URLs and need two to three screenshots for each one (to document the breakpoints), each screenshot reflecting domain and width in its filename. Is it possible to define global parameters and maybe even set placeholders for the filenames to be able to just feed a list of said URLs?

I couldn't find anything in the documentation, and I thought I'd ask. As a workaround, I could try automating the creation of the YAML file. I don't know though if this would be the most elegant way to do it?

**Comment by simonw** [comment]
You're right: at the moment the most elegant way to do this is to automate creation of the YAML file - something like this:

```yaml
- url: https://simonwillison.net/
  output: standard.png
  height: 800
- url: https://simonwillison.net/
  output: mobile.png
  width: 400
  height: 600
```
