### ISSUE TITLE
Design and implement selector shots

### ISSUE THREAD

**Issue by simonw** [simonw/shot-scraper#8]
Goal here is to be able to take a screenshot of a specific component of the page, identified by a CSS selector.

Should work for both multi and single shot mode.

**Comment by simonw** [comment]
https://playwright.dev/python/docs/screenshots

```python
page.locator(".header").screenshot(path="screenshot.png")
```

**Comment by simonw** [comment]
In single shot mode:

    shot-scraper https://simonwillison.net -s "#bighead"

In YAML:

```yaml
- url: https://simonwillison.net/
  output: simonwillison.net.png
  selector: "#bighead"
```

**Comment by simonw** [comment]
Testing `multi` with this `demo.yml` file:

```yaml
- output: example.com.png
  url: http://www.example.com/
- output: w3c.org.png
  url: https://www.w3.org/
- output: simonwillison-bighead.png
  url: https://simonwillison.net/
  selector: "#bighead"
```

```
% shot-scraper multi demo.yml
Screenshot of 'http://www.example.com/' written to 'example.com.png'
Screenshot of 'https://www.w3.org/' written to 'w3c.org.png'
Screenshot of '#bighead' on 'https://simonwillison.net/' written to 'simonwillison-bighead.png'
```
That last one produced this:

![simonwillison-bighead](https://user-images.githubusercontent.com/9599/157521646-105340df-cc4e-44d7-8339-b465e6d475ca.png)
